import React from 'react';
import { StyleSheet, View, Text, ScrollView } from 'react-native';
import { Card } from 'react-native-elements';

const VitalsReport = ({ vitalsData, patientName }) => {
  const currentDate = new Date().toLocaleString();

  return (
    <ScrollView style={styles.container}>
      <Card containerStyle={styles.card}>
        <View style={styles.headerSection}>
          <Text style={styles.hospitalName}>INHOZ HOSPITAL</Text>
          <Text style={styles.reportTitle}>Vitals Report</Text>
        </View>

        <View style={styles.patientInfo}>
          <View style={styles.infoRow}>
            <Text style={styles.label}>Patient Name:</Text>
            <Text style={styles.value}>{patientName}</Text>
          </View>
          <View style={styles.infoRow}>
            <Text style={styles.label}>Date & Time:</Text>
            <Text style={styles.value}>{currentDate}</Text>
          </View>
        </View>

        <View style={styles.tableContainer}>
          <View style={styles.tableHeader}>
            <Text style={[styles.tableCell, styles.headerCell, styles.parameterCell]}>Parameter</Text>
            <Text style={[styles.tableCell, styles.headerCell, styles.valueCell]}>Value</Text>
            <Text style={[styles.tableCell, styles.headerCell, styles.statusCell]}>Status</Text>
            <Text style={[styles.tableCell, styles.headerCell, styles.rangeCell]}>Normal Range</Text>
          </View>

          {Object.entries(vitalsData).map(([key, data], index) => {
            const ranges = {
              temperature: '36.5-37.5°C',
              pulse: '60-100 bpm',
              heartRate: '60-100 bpm',
              spO2: '95-100%',
              ivLevel: '20-100%',
              bloodPressure: '90/60-120/80 mmHg'
            };

            return (
              <View 
                key={key}
                style={[
                  styles.tableRow,
                  index % 2 === 0 ? styles.evenRow : styles.oddRow
                ]}
              >
                <Text style={[styles.tableCell, styles.parameterCell]}>
                  {key.charAt(0).toUpperCase() + key.slice(1)}
                </Text>
                <Text style={[styles.tableCell, styles.valueCell]}>
                  {data.value} {data.unit}
                </Text>
                <Text style={[
                  styles.tableCell, 
                  styles.statusCell,
                  { color: getStatusColor(data.status) }
                ]}>
                  {data.status}
                </Text>
                <Text style={[styles.tableCell, styles.rangeCell]}>
                  {ranges[key]}
                </Text>
              </View>
            );
          })}
        </View>

        <View style={styles.footer}>
          <Text style={styles.footerText}>Generated by INHOZ Medical System</Text>
          <Text style={styles.footerNote}>
            This is an electronically generated report
          </Text>
        </View>
      </Card>
    </ScrollView>
  );
};

const getStatusColor = (status) => {
  switch (status.toLowerCase()) {
    case 'normal':
      return '#4CAF50';
    case 'high':
      return '#FF5722';
    case 'low':
      return '#F44336';
    default:
      return '#666';
  }
};

const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: '#f5f5f5',
  },
  card: {
    borderRadius: 8,
    padding: 15,
    marginBottom: 20,
  },
  headerSection: {
    alignItems: 'center',
    marginBottom: 20,
    borderBottomWidth: 2,
    borderBottomColor: '#4a90e2',
    paddingBottom: 15,
  },
  hospitalName: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#4a90e2',
    marginBottom: 5,
  },
  reportTitle: {
    fontSize: 18,
    color: '#666',
  },
  patientInfo: {
    marginBottom: 20,
  },
  infoRow: {
    flexDirection: 'row',
    marginBottom: 8,
  },
  label: {
    width: 100,
    fontWeight: 'bold',
    color: '#333',
  },
  value: {
    flex: 1,
    color: '#666',
  },
  tableContainer: {
    borderWidth: 1,
    borderColor: '#ddd',
    borderRadius: 4,
    marginBottom: 20,
  },
  tableHeader: {
    flexDirection: 'row',
    backgroundColor: '#4a90e2',
  },
  tableRow: {
    flexDirection: 'row',
    borderTopWidth: 1,
    borderTopColor: '#ddd',
  },
  evenRow: {
    backgroundColor: '#fff',
  },
  oddRow: {
    backgroundColor: '#f9f9f9',
  },
  tableCell: {
    padding: 12,
    fontSize: 14,
  },
  headerCell: {
    color: '#fff',
    fontWeight: 'bold',
  },
  parameterCell: {
    flex: 2,
  },
  valueCell: {
    flex: 1.5,
  },
  statusCell: {
    flex: 1.5,
    fontWeight: 'bold',
  },
  rangeCell: {
    flex: 2,
  },
  footer: {
    marginTop: 20,
    paddingTop: 15,
    borderTopWidth: 1,
    borderTopColor: '#ddd',
    alignItems: 'center',
  },
  footerText: {
    color: '#666',
    marginBottom: 5,
  },
  footerNote: {
    color: '#999',
    fontSize: 12,
    fontStyle: 'italic',
  },
});

export default VitalsReport; 